# Generated by Django 3.1.7 on 2021-06-23 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
                ('tipoDeUsuario', models.IntegerField(choices=[(0, 'ADMIN'), (1, 'USER')])),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeVaga', models.CharField(max_length=40)),
                ('faixaSalario', models.IntegerField(choices=[(0, 'Até 1.000'), (1, 'De 1.000 a 2.000'), (2, 'De 2.000 a 3.000'), (3, 'Acima de 3.000')])),
                ('escolaridadeMinima', models.IntegerField(choices=[(0, 'Ensino Fundamental'), (1, 'Ensino médio'), (2, 'Tecnólogo'), (3, 'Ensino Superior'), (4, 'Pós / MBA / Mestrado'), (5, 'Doutorado')])),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioVaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretensaoSalario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ultimaEscolaridade', models.IntegerField(choices=[(0, 'Ensino Fundamental'), (1, 'Ensino médio'), (2, 'Tecnólogo'), (3, 'Ensino Superior'), (4, 'Pós / MBA / Mestrado'), (5, 'Doutorado')])),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usuario')),
                ('vagas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vaga')),
            ],
        ),
    ]
