# Generated by Django 3.1.7 on 2021-06-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariovaga',
            name='experiencia',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usuariovaga',
            name='objetivo',
            field=models.TextField(default=''),
        ),
    ]
