# Generated by Django 3.1.7 on 2021-06-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_vaga_requisitos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariovaga',
            name='objetivo',
        ),
    ]
