# Generated by Django 3.1.7 on 2021-06-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_usuariovaga_objetivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariovaga',
            old_name='usuarios',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='usuariovaga',
            old_name='vagas',
            new_name='vaga',
        ),
    ]
